# Generated by Django 5.0.6 on 2024-06-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationOfPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenume', models.CharField(max_length=100)),
                ('nume', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('număr_telefon', models.CharField(max_length=30)),
                ('număr_adulți', models.IntegerField()),
                ('număr_copii', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalizedInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_mireasă', models.CharField(max_length=100)),
                ('nume_mire', models.CharField(max_length=100)),
                ('dată_eveniment', models.DateField()),
                ('părinții_miresei', models.CharField(max_length=100)),
                ('părinții_mirelui', models.CharField(max_length=100)),
                ('nume_nașă', models.CharField(max_length=100)),
                ('nume_naș', models.CharField(max_length=100)),
                ('nume_biserică', models.CharField(max_length=100)),
                ('ora_cununie_religioasă', models.TimeField()),
                ('local_petrecere', models.CharField(max_length=100)),
                ('ora_petrecere', models.TimeField()),
            ],
        ),
    ]
