# Generated by Django 5.0.6 on 2024-06-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationofpresence',
            name='confirmare_prezență',
            field=models.CharField(choices=[('DA', 'DA'), ('NU', 'NU')], default='DA', max_length=3),
        ),
    ]
